apiVersion: apps/v1
kind: Deployment
rating:
  name:  rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    rating:
      labels:
        app: rating 
    spec:
      containers:
      - name:  rating
        image:  syasyayas/rating:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  8082


